[package]
name = "rusty_igdb"
version = "0.3.2"
edition = "2021"
description = "A simple IGDB (Internet Game Database) API wrapper for Rust users"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.99"
serde_qs = "0.12.0"

[features]
default = [
  "game",
  "character",
  "genre",
  "platform",
  "collection",
  "theme",
]
game = []
character = []
genre = []
platform = []
collection = []
theme = []
