[package]
name = "igdb"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.99"
serde_qs = "0.12.0"

[features]
default = ["game", "character", "genre"]
game = []
character = []
genre = []
